### PR TITLE
Adding g0teborg.se to managed domains

### PR DESCRIPTION
**Pull request by ThenWho**

### CODE REVIEW

**Comment by patcon** [comment]
Yay! First collectivized domain :)

**Review by patcon — APPROVED** [review]
LGTM!

**Comment by patcon** [comment]
k updated! Cloudflare now has _just_ these records you added here.

When you're ready, just point your nameservers as described in docs.

Note that you existing ovh nameservers had lots of default entries:
https://github.com/g0v-network/domains/runs/2033156191?check_suite_focus=true#step:4:55

You'll need to import them here if you want them to still stick around (ie. MX records, FTP stuff, etc etc) :)

**Comment by ThenWho** [comment]
Thanks Patrick! I didn't include them intentionally - if needed I might carry over maybe one, but that's it. Time will tell 🙂

**Comment by patcon** [comment]
Done and done! http://g0teborg.se

**Comment by patcon** [comment]
https://g0teborg.se now works better. Related: https://github.com/g0v-network/domains/issues/18

**Pull request merged**
